version: '3.7'

services:

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2/


  bweb:
    container_name: web2
    build:
      context: support
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./support:/usr/src/support
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./support
    command: celery -A Support worker -l info
    volumes:
      - ./support:/usr/src/support
    env_file: .env
    depends_on:
      - bweb
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_data: