version: '3.7'

services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: BUYB2QAZ
      POSTGRES_USER: postgres
      POSTGRES_DB: Support_db
    restart: always

  bweb:
    container_name: web2
    build:
      context: support
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/support/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./support:/usr/src/support
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./support
    command: celery -A Support worker -l info
    volumes:
      - ./support:/usr/src/support
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - bweb
      - redis

  redis:
    image: redis:6-alpine

volumes:
  postgres_data: